[project]
name = "2025-04-15-code-generation-small-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.83.0",
    "pytest>=8.3.5",
]
